[book]
title = "Ржачина By Example"
description = "A description"
author = "The Ржачина Community"

[output.html]
google-analytics="UA-142155799-8"
additional-css = ["theme/outdated.css"]

[output.html.playpen]
editable = true
editor = "ace"
